export enum Body {
    "RECHARGE_TITLE" = 'Recharge Title',
    "YEAR" = "Fiscal Year",
    "AMMOUNT" = 'Grand Amount',
    "CATEGORY" = 'Category',
    "NAME" = 'Name',
    "DESIGNATION" = 'Designation',
    "EMAIL" = 'Email',
    "MOBILE_NO" = 'Mobile No',
    "RECHARGE_TITLE_DATA" = 'Consanguinity and Its Impact on Probability of Autism in Inbred. Community of Bangladesh.',
    "YEAR_DATA" = '2020-2021',
    "AMMOUNT_DATA" = '30,00,000 tk',
    "FELLOWSHIP" = 'Fellowship',
    "NAME_DATA" = 'Dr. Profulla C. Sarker',
    "DEG_DATA" = 'Vice Chancellor, Royal University of Dhaka, Bangladesh.',
    "EMAIL_DATA" = 'profullosarker2123@gmail.com',
    "MOBILE_DATA" = '01767666666',
    "AGREEMENT" = '>> Agreement Information',
    "PROFILE" = '>> Profile Information',
    "PROPOSAL" = '>> Proposal Information',
    "PROFILE_MARKS" = '>> Profile Marks',
    "PROPOSAL_MARKS" = '>> Proposal Marks',
    "PRESENTATION" = 'Presentation',
    "DATE" = 'Date',
    "TYPE" = 'Type',
    "DOWNLOAD" = 'Download',
    "GRANT" = 'Grant Information',
    "SL" = 'SL',
    "TITLE" = 'Title',
    "RECEIVED_DATE" = 'Received Date',
    "AMOUNT" = 'Amount'


}